version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: geek_denki_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: geek_denki
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data:
